"""Client entrypoint — thin wiring only. Generated by `brickctl scaffold`.

Reads the single `config.yaml`, validates each brick's section against that
brick's model (omitted keys fall back to the brick's defaults), wires sub-brick
injections, and runs the pipeline stages in the order given by `pipeline:`.
This file is generic across clients; all client-specific behavior lives in
`config.yaml`.
"""
from __future__ import annotations

import importlib
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "engines"))
# Resolve relative config paths (e.g. ./data/in) against the client project.
os.chdir(HERE)

from brickkit import load_bundle, run_pipeline, validate_section, wire  # noqa: E402


def build():
    """Load config.yaml, import bricks, validate sections, inject sub-bricks.
    Returns (bound_by_name, ordered_stage_list)."""
    bundle = load_bundle(HERE / "config.yaml")
    stage_names = bundle["pipeline"]
    brick_names = [k for k in bundle if k != "pipeline"]

    modules = {name: importlib.import_module(name) for name in brick_names}
    configs = {
        name: validate_section(modules[name], bundle[name]) for name in brick_names
    }
    bound = wire(modules, configs)
    return bound, [bound[name] for name in stage_names]


def main():
    bound, stages = build()
    result = run_pipeline(stages, None)
    print(result)
    return result


if __name__ == "__main__":
    main()
